# Generated by Django 5.1 on 2026-10-01 04:56

from django.db import migrations


class Migration(migrations.Migration):

    # The combined migration creates Coupon and CouponUsage. Keep this
    # historical migration as a no-op after it to avoid creating Coupon twice.
    dependencies = [
        ('orders', '0006_coupon_couponusage'),
    ]

    operations = []
